import { HistoricPlace, Project, DashboardStats } from '@/types';

export const samplePlaces: HistoricPlace[] = [
  {
    id: '1',
    name_en: 'Pashupatinath Temple',
    name_ne: 'पशुपतिनाथ मन्दिर',
    description_en: 'Pashupatinath Temple is a famous and sacred Hindu temple dedicated to Pashupatinath (Lord Shiva). Located on the banks of the Bagmati River in Kathmandu, it is one of the most significant Hindu temples in the world and a UNESCO World Heritage Site.',
    description_ne: 'पशुपतिनाथ मन्दिर पशुपतिनाथ (भगवान शिव) लाई समर्पित एक प्रसिद्ध र पवित्र हिन्दू मन्दिर हो। काठमाडौंमा बागमती नदीको किनारमा अवस्थित, यो विश्वका सबैभन्दा महत्त्वपूर्ण हिन्दू मन्दिरहरूमध्ये एक हो र यूनेस्को विश्व सम्पदा स्थल हो।',
    latitude: 27.7109,
    longitude: 85.3484,
    category: 'temple',
    photo_urls: ['https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Pashupatinath_Temple.jpg/1200px-Pashupatinath_Temple.jpg'],
    opening_hours: '4:00 AM - 12:00 PM, 5:00 PM - 9:00 PM',
    entry_fee: 'NPR 1000 (Foreigners)',
    rating: 4.8,
    review_count: 2450,
    historical_period: '5th Century AD',
    is_featured: true,
    nearby_place_ids: ['2', '3'],
    address: 'Pashupati Nath Road',
    city: 'Kathmandu',
    province: 'Bagmati',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name_en: 'Boudhanath Stupa',
    name_ne: 'बौद्धनाथ स्तूप',
    description_en: 'Boudhanath is a stupa in Kathmandu, Nepal. The stupa\'s massive mandala makes it one of the largest spherical stupas in Nepal and a UNESCO World Heritage Site.',
    description_ne: 'बौद्धनाथ नेपालको काठमाडौंमा एक स्तूप हो। स्तूपको विशाल मण्डलले यसलाई नेपालका सबैभन्दा ठूला गोलाकार स्तूपहरूमध्ये एक बनाउँछ र यूनेस्को विश्व सम्पदा स्थल हो।',
    latitude: 27.7215,
    longitude: 85.3620,
    category: 'stupa',
    photo_urls: ['https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Boudhanath_stupa.jpg/1200px-Boudhanath_stupa.jpg'],
    opening_hours: '6:00 AM - 9:00 PM',
    entry_fee: 'NPR 400 (Foreigners)',
    rating: 4.9,
    review_count: 3200,
    historical_period: '14th Century',
    is_featured: true,
    nearby_place_ids: ['1'],
    address: 'Boudha',
    city: 'Kathmandu',
    province: 'Bagmati',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name_en: 'Swayambhunath (Monkey Temple)',
    name_ne: 'स्वयम्भूनाथ (बाँदर मन्दिर)',
    description_en: 'Swayambhunath is an ancient religious complex atop a hill in the Kathmandu Valley, also known as the Monkey Temple.',
    description_ne: 'स्वयम्भूनाथ काठमाडौं उपत्यकाको एउटा पहाडको टुप्पोमा एक प्राचीन धार्मिक परिसर हो, जसलाई बाँदर मन्दिर पनि भनिन्छ।',
    latitude: 27.7149,
    longitude: 85.2904,
    category: 'stupa',
    photo_urls: [],
    opening_hours: '5:00 AM - 8:00 PM',
    entry_fee: 'NPR 200 (Foreigners)',
    rating: 4.7,
    review_count: 2800,
    historical_period: '5th Century',
    is_featured: true,
    nearby_place_ids: ['4'],
    address: 'Swayambhu',
    city: 'Kathmandu',
    province: 'Bagmati',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    name_en: 'Kathmandu Durbar Square',
    name_ne: 'काठमाडौं दरबार स्क्वायर',
    description_en: 'Kathmandu Durbar Square is in front of the old royal palace of the former Kathmandu Kingdom and is one of three Durbar Squares in the Kathmandu Valley.',
    description_ne: 'काठमाडौं दरबार स्क्वायर पूर्व काठमाडौं राज्यको पुरानो राजदरबारको अगाडि छ र काठमाडौं उपत्यकाका तीन दरबार स्क्वायरहरूमध्ये एक हो।',
    latitude: 27.7045,
    longitude: 85.3065,
    category: 'durbar',
    photo_urls: [],
    opening_hours: '7:00 AM - 7:00 PM',
    entry_fee: 'NPR 1000 (Foreigners)',
    rating: 4.6,
    review_count: 1900,
    historical_period: '12th-18th Century',
    is_featured: true,
    nearby_place_ids: ['3'],
    address: 'Basantapur',
    city: 'Kathmandu',
    province: 'Bagmati',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    name_en: 'Patan Durbar Square',
    name_ne: 'पाटन दरबार स्क्वायर',
    description_en: 'Patan Durbar Square is situated at the centre of Lalitpur city, one of the three Durbar Squares in the Kathmandu Valley.',
    description_ne: 'पाटन दरबार स्क्वायर ललितपुर शहरको केन्द्रमा अवस्थित छ, काठमाडौं उपत्यकाका तीन दरबार स्क्वायरहरूमध्ये एक।',
    latitude: 27.6726,
    longitude: 85.3247,
    category: 'durbar',
    photo_urls: [],
    opening_hours: '7:00 AM - 7:00 PM',
    entry_fee: 'NPR 1000 (Foreigners)',
    rating: 4.8,
    review_count: 2100,
    historical_period: '12th-18th Century',
    is_featured: false,
    nearby_place_ids: [],
    address: 'Mangal Bazar',
    city: 'Lalitpur',
    province: 'Bagmati',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

export const sampleProjects: Project[] = [
  {
    id: 'p1',
    name: 'Pashupatinath Temple Restoration',
    description: 'Comprehensive restoration of the main temple complex including structural repairs, stone conservation, and drainage improvement.',
    location_name: 'Pashupatinath Temple, Kathmandu',
    latitude: 27.7109,
    longitude: 85.3484,
    start_date: '2024-01-15',
    end_date: '2025-06-30',
    status: 'ongoing',
    category: 'restoration',
    contractor: 'Nepal Heritage Construction Pvt. Ltd.',
    budget_total: 15000000,
    budget_spent: 8500000,
    physical_progress: 62,
    financial_progress: 57,
    photos: [],
    notes: 'Phase 1 (structural repairs) completed. Phase 2 (stone conservation) in progress.',
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2024-02-20T00:00:00Z',
    milestones: [
      {
        id: 'm1',
        title: 'Site Survey & Assessment',
        description: 'Complete structural assessment of the temple complex',
        due_date: '2024-02-15',
        completed: true,
        completed_date: '2024-02-10',
      },
      {
        id: 'm2',
        title: 'Phase 1: Structural Repairs',
        description: 'Foundation and wall structural repairs',
        due_date: '2024-06-30',
        completed: true,
        completed_date: '2024-06-25',
      },
      {
        id: 'm3',
        title: 'Phase 2: Stone Conservation',
        description: 'Conservation of carved stone elements',
        due_date: '2024-12-31',
        completed: false,
      },
      {
        id: 'm4',
        title: 'Phase 3: Drainage & Landscaping',
        description: 'Improve drainage system and landscape restoration',
        due_date: '2025-06-30',
        completed: false,
      },
    ],
    ping_history: [
      {
        id: 'ping1',
        project_id: 'p1',
        latitude: 27.7109,
        longitude: 85.3484,
        timestamp: '2024-02-20T10:30:00Z',
        physical_progress: 62,
        financial_progress: 57,
        notes: 'Stone conservation work ongoing. 40% of carved elements treated.',
        photos: [],
        pinged_by: 'Site Engineer Ram Prasad',
      },
      {
        id: 'ping2',
        project_id: 'p1',
        latitude: 27.7110,
        longitude: 85.3485,
        timestamp: '2024-01-20T09:00:00Z',
        physical_progress: 45,
        financial_progress: 38,
        notes: 'Structural repairs completed for north wing.',
        photos: [],
        pinged_by: 'Project Manager Sita Devi',
      },
    ],
  },
  {
    id: 'p2',
    name: 'Boudhanath Stupa Conservation',
    description: 'Conservation and preservation of the Boudhanath Stupa including whitewashing, gold spire maintenance, and surrounding area development.',
    location_name: 'Boudhanath Stupa, Kathmandu',
    latitude: 27.7215,
    longitude: 85.3620,
    start_date: '2024-03-01',
    end_date: '2024-12-31',
    status: 'ongoing',
    category: 'conservation',
    contractor: 'Buddhist Heritage Trust',
    budget_total: 8000000,
    budget_spent: 3200000,
    physical_progress: 40,
    financial_progress: 40,
    photos: [],
    notes: 'Annual maintenance and conservation work.',
    created_at: '2024-02-20T00:00:00Z',
    updated_at: '2024-02-20T00:00:00Z',
    milestones: [
      {
        id: 'm5',
        title: 'Whitewashing',
        description: 'Annual whitewashing of the stupa dome',
        due_date: '2024-05-31',
        completed: false,
      },
      {
        id: 'm6',
        title: 'Gold Spire Maintenance',
        description: 'Maintenance and gilding of the gold spire',
        due_date: '2024-08-31',
        completed: false,
      },
    ],
    ping_history: [],
  },
  {
    id: 'p3',
    name: 'Patan Durbar Square Infrastructure',
    description: 'Infrastructure improvement including visitor pathways, lighting, signage, and accessibility features.',
    location_name: 'Patan Durbar Square, Lalitpur',
    latitude: 27.6726,
    longitude: 85.3247,
    start_date: '2023-06-01',
    end_date: '2024-03-31',
    status: 'completed',
    category: 'infrastructure',
    contractor: 'Lalitpur Metropolitan City',
    budget_total: 5000000,
    budget_spent: 4850000,
    physical_progress: 100,
    financial_progress: 97,
    photos: [],
    notes: 'Project completed successfully. Minor punch list items remaining.',
    created_at: '2023-05-15T00:00:00Z',
    updated_at: '2024-03-31T00:00:00Z',
    milestones: [
      {
        id: 'm7',
        title: 'Pathway Construction',
        description: 'Stone pathway construction around the square',
        due_date: '2023-10-31',
        completed: true,
        completed_date: '2023-10-28',
      },
      {
        id: 'm8',
        title: 'Lighting Installation',
        description: 'Heritage lighting installation',
        due_date: '2024-01-31',
        completed: true,
        completed_date: '2024-01-25',
      },
      {
        id: 'm9',
        title: 'Signage & Accessibility',
        description: 'Bilingual signage and accessibility ramps',
        due_date: '2024-03-31',
        completed: true,
        completed_date: '2024-03-28',
      },
    ],
    ping_history: [],
  },
];

export function getDashboardStats(): DashboardStats {
  const totalBudget = sampleProjects.reduce((sum, p) => sum + p.budget_total, 0);
  const totalSpent = sampleProjects.reduce((sum, p) => sum + p.budget_spent, 0);
  const avgPhysical = sampleProjects.reduce((sum, p) => sum + p.physical_progress, 0) / sampleProjects.length;
  const avgFinancial = sampleProjects.reduce((sum, p) => sum + p.financial_progress, 0) / sampleProjects.length;

  const placesByCategory: Record<string, number> = {};
  samplePlaces.forEach(p => {
    placesByCategory[p.category] = (placesByCategory[p.category] || 0) + 1;
  });

  const projectsByStatus: Record<string, number> = {};
  sampleProjects.forEach(p => {
    projectsByStatus[p.status] = (projectsByStatus[p.status] || 0) + 1;
  });

  return {
    total_places: samplePlaces.length,
    total_projects: sampleProjects.length,
    ongoing_projects: sampleProjects.filter(p => p.status === 'ongoing').length,
    completed_projects: sampleProjects.filter(p => p.status === 'completed').length,
    total_budget: totalBudget,
    total_spent: totalSpent,
    avg_physical_progress: Math.round(avgPhysical),
    avg_financial_progress: Math.round(avgFinancial),
    places_by_category: placesByCategory,
    projects_by_status: projectsByStatus,
  };
}
